---
- name: Add tailscale APT repository
  become: true
  block:
    - name: GPG key
      ansible.builtin.get_url:
        url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg"
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: APT source 
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
        state: present
        filename: tailscale